-- =====================================================================
-- archive_photos SEED — load Naldo's 211 resolved archive photos
-- (#167 P1 slice 1). Generated from
-- docs/superpowers/specs/data/2026-07-23-resolved-photos-cumulative.csv.
--
-- One INSERT per Drive file. resolved_customer_id resolves the naming pass's
-- 8-char customer-id prefix to the full uuid via a subquery (verified 1:1
-- read-only at generate time — see the VERIFY block at the foot of this file,
-- which re-checks it at APPLY time). ON CONFLICT (drive_file_id) DO NOTHING
-- makes this idempotent — re-running never duplicates or clobbers reviewer edits.
--
-- 158 install photos -> status 'pending' (of those, 1 carry a manually
-- typed address that matched no CRM contact -> not_in_crm); 52 non-installs ->
-- 'excluded' + classification 'other'; 1 name-only (no address yet) ->
-- 'pending' + not_in_crm, name in reviewer_notes.
--
-- HOW TO APPLY: run AFTER 2026-07-23-archive-photos.sql. Paste + Run in the
-- Supabase SQL Editor, then read the VERIFY block's output. Idempotent.
-- =====================================================================

insert into public.archive_photos
  (drive_file_id, source_folder, original_title, classification, resolved_address,
   resolved_customer_id, resolved_customer_ref, resolved_name, not_in_crm,
   status, reviewer_notes)
values
  ('1x-D_1tENEZSG4DoZY8aLqVRWrg3g1nff', 'Homes without Logo v2', 'IMG_0541.HEIC', 'install_night', '69 Grand Boulevard Massapequa Park', null, null, null, false, 'pending', null),
  ('1SRjMvduixZ2JiIXi9TrWqORqAn4FLyKT', 'Homes without Logo v2', 'IMG_0585.HEIC', 'install_night', null, (select id from public.customers where left(id::text,8) = 'b906bcac' limit 1), 'b906bcac', 'deborah sande', false, 'pending', null),
  ('1wy-Nc4nRrTT-lYEj8uHOQbeeK7HpnJNp', 'Homes without Logo v2', 'IMG_0600.HEIC', 'install_night', '32 Walnut Road Amityville', null, null, null, false, 'pending', null),
  ('1LaUojqkS8pIHneJAwmzL9vKRumPPAgrE', 'Homes without Logo v2', 'IMG_0701.HEIC', 'install_night', '32 Walnut Road Amityville', null, null, null, false, 'pending', null),
  ('1BGSbu_3pxzUrd31HATTXbx87EtGazaMq', 'Homes without Logo v2', 'IMG_0726.HEIC', 'install_night', '37 Camp Road Massapequa', null, null, null, false, 'pending', null),
  ('1gWbGuh5XwK1PaR9QSBI1tOqUJPEyb01Q', 'Homes without Logo v2', 'IMG_0738.HEIC', 'install_night', '152 Harbor Lane, Massapequa Park 11762', (select id from public.customers where left(id::text,8) = 'e16366b3' limit 1), 'e16366b3', 'John Mezzetta', false, 'pending', null),
  ('1C-ATAzrVvvX8gUo3q9AyMeK66F8_3VsE', 'Homes without Logo v2', 'IMG_0901.HEIC', 'install_night', null, null, null, 'tal', true, 'pending', 'needs CRM lookup: tal'),
  ('11n7UxlffQK93YLxEkdZweRvu5cQRpt8f', 'Homes without Logo v2', 'IMG_0922.HEIC', 'install_night', '1255 East 57th Street Brooklyn', null, null, null, false, 'pending', null),
  ('1hY8sEBCrdbuA6j8i7D0jW5MkMJRFfogK', 'Homes without Logo v2', 'IMG_0933.HEIC', 'install_night', '14 East Street Amityville', null, null, null, false, 'pending', null),
  ('10Wa6q3NYJ-GtFr523wIPEeeUGmEbhd20', 'Homes without Logo v2', 'IMG_0957.HEIC', 'install_night', '159 Melville Road, Farmingdale 11735', (select id from public.customers where left(id::text,8) = '31bb07ec' limit 1), '31bb07ec', 'Patricia Brosnan', false, 'pending', null),
  ('1cO3df8g6DXpJn_opTmguiojyRHRq_kHz', 'Homes without Logo v2', 'IMG_1252.HEIC', 'install_night', '19 Elgar Street, East Northport 11731', (select id from public.customers where left(id::text,8) = '34c47f2a' limit 1), '34c47f2a', 'Joe Mir', false, 'pending', null),
  ('1jeWbnOhTSJ5CNhr7y5ktSmKR7TLw8l98', 'Homes without Logo v2', 'IMG_1271.HEIC', 'install_night', '13 Santapogue Dr, Lindenhurst 11757', (select id from public.customers where left(id::text,8) = 'a9602ea0' limit 1), 'a9602ea0', 'Thomas Humel', false, 'pending', null),
  ('1IL5-gEF-UCydWNpScAwwZqhEauftSwAK', 'Homes without Logo v2', 'IMG_1276.HEIC', 'install_night', '131 Grand Avenue Lindenhurst', null, null, null, false, 'pending', null),
  ('1lTP1uML7aPsdDXUf9wS-_s9XdzHS5dz1', 'Homes without Logo v2', 'IMG_1367.HEIC', 'install_night', '21 Dale Drive Farmingdale', null, null, null, false, 'pending', null),
  ('1BRIPIJ16J41gyUUhiPPowah9ox2ZiIcQ', 'Homes without Logo v2', 'IMG_1386.HEIC', 'install_night', '191 Main Pkwy W, Plainview 11803', (select id from public.customers where left(id::text,8) = 'e993bcd2' limit 1), 'e993bcd2', 'David Antonacci', false, 'pending', null),
  ('1L3VH0mBMvpSkxXlwlrOAkO9lUdxVWmm0', 'Homes without Logo v2', 'IMG_1404.HEIC', 'install_night', '225 Circle Road, Syosset 11791', (select id from public.customers where left(id::text,8) = 'bbf6824a' limit 1), 'bbf6824a', 'Morgan Hayes', false, 'pending', null),
  ('1ssFRM58KxlMxMCTCHz2keCfvWjXROgW4', 'Homes without Logo v2', 'IMG_1627.HEIC', 'install_night', '137 Cold Spring Road Syosset', null, null, null, false, 'pending', null),
  ('1lH-mR2ljJzdpUTduFylzvdWwAXjNgSle', 'Homes without Logo v2', 'DJI_20241118_221215_031.jpg', 'install_night', '163 Brewster Road, Massapequa 11758', (select id from public.customers where left(id::text,8) = '655feaad' limit 1), '655feaad', 'Angelo Ditroia', false, 'pending', null),
  ('11kqroNgL3FBsKBBVdwdH-q1PZu0Q91P-', 'Homes without Logo v2', 'DJI_20241118_221330_585.JPG', 'install_night', '160 Brewster Rd, Massapequa, NY 11758', null, null, null, false, 'pending', null),
  ('1x4nWsq6sSGDDdkrVwWJYZhEW7M5wvGsW', 'Homes without Logo v2', 'DJI_20241119_225837_511.JPG', 'install_night', '100 Browns, Huntington, NY 11743', null, null, null, false, 'pending', null),
  ('1N-vVbdBy7so_MwtT0krezsEUYjAWSVPy', 'Homes without Logo v2', 'DJI_20241130_200555_489.jpg', 'install_night', '12 Beaumont Drive Melville', null, null, null, false, 'pending', null),
  ('19ARh_j2D8dad1C-2IcznH0WrZZOOPeg9', 'Homes without Logo v2', 'DJI_20241130_204437_327.jpg', 'install_night', '426 Wolf Hill Road Dix Hills', null, null, null, false, 'pending', null),
  ('1ZMn1ZYwBu7tBZ129jILCTHdYSACDBUcR', 'Homes without Logo v2', 'DJI_20241130_210819_998.jpg', 'install_night', '25 Corsa Street Dix Hills', null, null, null, false, 'pending', null),
  ('1cBcNXQnaSHBzz4io__2UMvb16IS5zzTV', 'Homes without Logo v2', 'DJI_20241130_235517_247.jpg', 'install_night', '31 White Cliff LnNesconset, NY 11767', null, null, null, false, 'pending', null),
  ('1ReZiu7dE3vmuXefwk5bLZ-yCx_pIDzYC', 'Homes without Logo', 'IMG_8125.HEIC', 'install_night', '31 White Cliff LnNesconset, NY 11767', null, null, null, false, 'pending', null),
  ('1PW62CWqQ7K5whP1pNLSUnGShMimp_qKl', 'Homes without Logo', 'DJI_20241119_225640_809_video.MP4', 'other', null, null, null, null, false, 'excluded', null),
  ('1BeXQI__oGuTN327fJCDFcsyoNH_O5FGa', 'Homes Without Logo (numbered img###.png)', 'img13.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1G3WNfiTZurnvbVQBaTVHNtthitOxUcPp', 'Homes Without Logo (numbered img###.png)', 'img14.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1e5k6fUibQUe9TmsHiUzbXZruC2qoq-MG', 'Homes Without Logo (numbered img###.png)', 'img15.png', 'install_night', '2 Marriott Plaza, Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1W1qc-dZOH-3fDAn8r3UlML3JPrF5jsdk', 'Homes Without Logo (numbered img###.png)', 'img16.png', 'install_night', '2 Marriott Plaza, Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1JEeYxLmDGnCgB1V9X3l79e0-52ayW2NV', 'Homes Without Logo (numbered img###.png)', 'img17.png', 'install_night', '6 Maggie Court, Nesconset, New York 11767', null, null, null, false, 'pending', null),
  ('1PG7q1Ii4l6F15EiLlnDYa7aRqN1JXpI-', 'Homes Without Logo (numbered img###.png)', 'img18.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1iLdL3aXAOxtm25hnSmCjkgaMSgTRxBh4', 'Homes Without Logo (numbered img###.png)', 'img19.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1uYz5-hGcXZlb2B408-ieboNmBEXUjnII', 'Homes Without Logo (numbered img###.png)', 'img20.png', 'install_night', '5 Harborfields Court, Greenlawn 11740', (select id from public.customers where left(id::text,8) = '9825677a' limit 1), '9825677a', 'Rohith Nandagiri', false, 'pending', null),
  ('1XYNYy8hJt7WjszANoC9GW9Z3QvEYb-12', 'Homes Without Logo (numbered img###.png)', 'img21.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1x4_q5vlh5YZZbAp6SaQ11Isdm1N3w1Iq', 'Homes Without Logo (numbered img###.png)', 'img22.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1ibiO1txhRReLlRPwPgFxS5hZ7rlr8WpN', 'Homes Without Logo (numbered img###.png)', 'img23.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1C6psJTdlP8EGRnUGYWTdcPH_ZYsvlyFn', 'Homes Without Logo (numbered img###.png)', 'img24.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('17Y2VYBJVu2QbC_Tt29khHT5_-caFNKRC', 'Homes Without Logo (numbered img###.png)', 'img25.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1chP0nlarIvGiSizv2Nztfwu9Mkni-KKf', 'Homes Without Logo (numbered img###.png)', 'img26.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1IdNLJtY9Ue48CUwZVpdgcq4tTQ_Z_xXs', 'Homes Without Logo (numbered img###.png)', 'img27.png', 'install_night', '163 Brewster Road, Massapequa 11758', (select id from public.customers where left(id::text,8) = '655feaad' limit 1), '655feaad', 'Angelo Ditroia', false, 'pending', null),
  ('1ezFHqqEbJSPrtSW3EH4Ui3SnHSe_n77L', 'Homes Without Logo (numbered img###.png)', 'img28.png', 'install_night', '319 West 15th Street Deer Park', null, null, null, false, 'pending', null),
  ('1mRAgiJlmDdHhdhYScewAb7GyWgBnSVsg', 'Homes Without Logo (numbered img###.png)', 'img29.png', 'install_night', '134 Larsen Drive, Amityville 11701', (select id from public.customers where left(id::text,8) = '94993ae6' limit 1), '94993ae6', 'Mr. Albert Belcher', false, 'pending', null),
  ('1kU1i5L6a5rusCS8npvtxoCo_TyLibRCQ', 'Homes Without Logo (numbered img###.png)', 'img30.png', 'install_night', '6 BIRCH ROAD AMITYVILLE NY 11701', null, null, null, false, 'pending', null),
  ('1kdzSfMzf28yV1fmNrO0psUV0iU-KNFxX', 'Homes Without Logo (numbered img###.png)', 'img31.png', 'install_night', '3775 New York Avenue, Seaford 11783', (select id from public.customers where left(id::text,8) = 'f1f7d096' limit 1), 'f1f7d096', 'Kathy Polera', false, 'pending', null),
  ('1rG9-QsD7Af_mRcC-ugIPqzxZKOhIOuAF', 'Homes Without Logo (numbered img###.png)', 'img32.png', 'install_night', '13 Santapogue Dr, Lindenhurst 11757', (select id from public.customers where left(id::text,8) = 'a9602ea0' limit 1), 'a9602ea0', 'Thomas Humel', false, 'pending', null),
  ('1SG6NCE2KpIxdv_PBW-CEeSlNESF3UUWx', 'Homes Without Logo (numbered img###.png)', 'img33.png', 'install_night', '8 Birch Rd, Amityville, NY 11701', null, null, null, false, 'pending', null),
  ('1dOTDc1kYwFiG9SvnFaHY7LKp63UnItMk', 'Homes Without Logo (numbered img###.png)', 'img34.png', 'install_night', '5 Birch Rd, Amityville, NY 11701', null, null, null, false, 'pending', null),
  ('10lMlx9gTxUnEDUmQPnVQqF3ZdAq3gh-8', 'Homes Without Logo (numbered img###.png)', 'img35.png', 'install_night', '16 Birch Road, Amityville 11701', (select id from public.customers where left(id::text,8) = 'f045da35' limit 1), 'f045da35', 'Margaret Cox', false, 'pending', null),
  ('1BberISkCembns4pSf2DPOaSLwt02pW8S', 'Homes Without Logo (numbered img###.png)', 'img36.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1Qtfg10Jpc4G8CTYsdEoYIhlvdfIJ3paG', 'Homes Without Logo (numbered img###.png)', 'img37.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1DWfjBLrq5rxqR9rsgsAW3zYfLPEF5OZh', 'Homes Without Logo (numbered img###.png)', 'img38.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1r3m48AE9aHXjRTo_lHA7Zyu-WHaI6KM7', 'Homes Without Logo (numbered img###.png)', 'img39.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1exzgiWYhnURWIfvKLd3IDOkwnxVXb4J1', 'Homes Without Logo (numbered img###.png)', 'img40.png', 'install_night', '15 East Nancy Place Massapequa', null, null, null, false, 'pending', null),
  ('1HXMP8vXqMjI3_aVmCI53KZSuofcekKMx', 'Homes Without Logo (numbered img###.png)', 'img41.png', 'install_night', '11 Winthrop Drive Dix Hills', null, null, null, false, 'pending', null),
  ('1cD_3XdIvgENSzbhqVMGxpA2o14Wep4sd', 'Homes Without Logo (numbered img###.png)', 'img42.png', 'install_night', '29 Sunset Road, Bay Shore 11706', (select id from public.customers where left(id::text,8) = 'd86f955d' limit 1), 'd86f955d', 'Dan Panessa', false, 'pending', null),
  ('1DALpLrCdeK-wz3WSLBcMPJdIMsJuOzg1', 'Homes Without Logo (numbered img###.png)', 'img43.png', 'install_night', '160 Brewster Rd, Massapequa, NY 11758', null, null, null, false, 'pending', null),
  ('10BMU1Sp36HzfDbQhJqxBhcYUAK-07b47', 'Homes Without Logo (numbered img###.png)', 'img44.png', 'install_night', '29 Sunset Road, Bay Shore 11706', (select id from public.customers where left(id::text,8) = 'd86f955d' limit 1), 'd86f955d', 'Dan Panessa', false, 'pending', null),
  ('1F8wYherIaQYp0ZrlFZTE5V4kQOLZYQfJ', 'Homes Without Logo (numbered img###.png)', 'img45.png', 'install_night', '5 Mason Court, East Northport 11731', (select id from public.customers where left(id::text,8) = '98710a65' limit 1), '98710a65', 'Carl Laurent', false, 'pending', null),
  ('11oLy4jJ8kURNmcOs1VbCGJWLbnrq8Fmb', 'Homes Without Logo (numbered img###.png)', 'img46.png', 'other', null, null, null, null, false, 'excluded', null),
  ('10RNCvT9A5LPzcgdG75F9gNvapuQahB7S', 'Homes Without Logo (numbered img###.png)', 'img47.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1cz61aTgfNJduosUVeEVJhbhT8j57y4vA', 'Homes Without Logo (numbered img###.png)', 'img48.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1fahp1G9M8fAznwEREUVFVSuniflao2Aq', 'Homes Without Logo (numbered img###.png)', 'img49.png', 'install_night', '21 Jamaica Ave, Greenlawn 11740', (select id from public.customers where left(id::text,8) = '45180514' limit 1), '45180514', 'Keith Simonsen', false, 'pending', null),
  ('18hf9o4Bfcr9U9EqmTDorOdaac8rb9ZLT', 'Homes Without Logo (numbered img###.png)', 'img50.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1gh_THrp7jA7mkLmxsR9g2YMcQ2aLlj9k', 'Homes Without Logo (numbered img###.png)', 'img51.png', 'install_night', '123 Soundview Terrace Northport', null, null, null, false, 'pending', null),
  ('1FTa2zzn-tkwyytrDYJfHPKRNrz1HEawF', 'Homes Without Logo (numbered img###.png)', 'img52.png', 'install_night', '123 Soundview Terrace Northport', null, null, null, false, 'pending', null),
  ('1KZfJAg-XCkPNjaWUlD40_DE8ON0VcvY1', 'Homes Without Logo (numbered img###.png)', 'img53.png', 'install_night', '19 Elgar Street, East Northport 11731', (select id from public.customers where left(id::text,8) = '34c47f2a' limit 1), '34c47f2a', 'Joe Mir', false, 'pending', null),
  ('1r8ROPNkAusOMj_WXon3XmJcdeSvx9FAf', 'Homes Without Logo (numbered img###.png)', 'img54.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1_PLzcAV3BGIv_4y8p2x-DVDpOE01Wzk7', 'Homes Without Logo (numbered img###.png)', 'img55.png', 'install_night', '25 Corsa Street Dix Hills', null, null, null, false, 'pending', null),
  ('1tKM1T0Bj56I5lKIAaDZ4C4pcu0jb3gqV', 'Homes Without Logo (numbered img###.png)', 'img56.png', 'install_night', '34 White Oak Street Deer Park', null, null, null, false, 'pending', null),
  ('1eLpDKmWbeuxcMGVx4yJxbOUhwIrCNZrq', 'Homes Without Logo (numbered img###.png)', 'img57.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1oBFVHxnctzZAtlOoEB3ccAvgW8TxJtiu', 'Homes Without Logo (numbered img###.png)', 'img58.png', 'install_night', '213 Secatogue Ln, West Islip 11795', (select id from public.customers where left(id::text,8) = 'e52156ea' limit 1), 'e52156ea', 'Genevieve McGuinness', false, 'pending', null),
  ('1m0b-9YLNigYgm11Mz45lF2jnXNUGvVpq', 'Homes Without Logo (numbered img###.png)', 'img59.png', 'install_night', '98 Bayway Avenue, Brightwaters 11718', (select id from public.customers where left(id::text,8) = 'd5316122' limit 1), 'd5316122', 'Tom Marra', false, 'pending', null),
  ('1_lV5aYvriDyUbJlLlHYts8pqfubn3-Vr', 'Homes Without Logo (numbered img###.png)', 'img60.png', 'install_night', '13 Brown Boulevard, Wyandanch 11798', (select id from public.customers where left(id::text,8) = '3b822e9a' limit 1), '3b822e9a', 'Mrs. Mrs. Jones', false, 'pending', null),
  ('1_vn12jYksXf_CzyN-cMzAz7GF5hs1DzE', 'Homes Without Logo (numbered img###.png)', 'img61.png', 'install_night', '23 Bridle Lane, Huntington Station 11746', (select id from public.customers where left(id::text,8) = '97d87eb2' limit 1), '97d87eb2', 'Severo Fernandes', false, 'pending', null),
  ('1H5H7d4vVpQjmMwThPsNQ8UWp2aFyYHF6', 'Homes Without Logo (numbered img###.png)', 'img63.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1xtZ-a4rO8qeYNPWSd8As2ddGbqkAM618', 'Homes Without Logo (numbered img###.png)', 'img64.png', 'other', null, null, null, null, false, 'excluded', null),
  ('19vky_upbm6YSqSPD9mxlhJd_3IAzCUnG', 'Homes Without Logo (numbered img###.png)', 'img65.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1vtXu8miz199B6CIb9hD6wqiJclbMCiwW', 'Homes Without Logo (numbered img###.png)', 'img66.png', 'install_night', '7 Sunburst Drive Deer Park', null, null, null, false, 'pending', null),
  ('1uiR5BeGHh14GNfytwZf89RO3MJWaQjPS', 'Homes Without Logo (numbered img###.png)', 'img67.png', 'install_night', '9 high ridge lane', null, null, null, false, 'pending', null),
  ('137AoqI2F35k1BezpAxxkT6dvFa7I2Fax', 'Homes Without Logo (numbered img###.png)', 'img68.png', 'install_night', '2 Marriott Plaza, Farmingdale, NY 11735', null, null, 'Two Marriott Plaza', false, 'pending', null),
  ('14v-psq0dxIBA31WW3tt8nP08wELIIKf2', 'Homes Without Logo (numbered img###.png)', 'img70.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1uRmeNjepGkOho1m_-V8BQqCtklizPPJp', 'Homes Without Logo (numbered img###.png)', 'img71.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1Z-szWGDidH-Wbu4PvL-59yhxG7bBRptI', 'Homes Without Logo (numbered img###.png)', 'img72.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1cRkM9p7JFRxqfFDS5cgWmkNvMnakwiwL', 'Homes Without Logo (numbered img###.png)', 'img73.png', 'install_night', '8 Grey Place West Babylon', null, null, null, false, 'pending', null),
  ('1gGd0Qht-LXaiOdEEvIC9foEorgGhvtuA', 'Homes Without Logo (numbered img###.png)', 'img74.png', 'install_night', '10 Barrington Place Melville', null, null, null, false, 'pending', null),
  ('1RjDlAHlg1vQPmPXDq3Ge6fQBfVrM4bmC', 'Homes Without Logo (numbered img###.png)', 'img75.png', 'install_night', '138 Country Club Drive, Commack 11725', (select id from public.customers where left(id::text,8) = 'a27de417' limit 1), 'a27de417', 'Vincent Barbieri', false, 'pending', null),
  ('1E4_F_HrOaaledSXDfOOR9utFJ8swC4hS', 'Homes Without Logo (numbered img###.png)', 'img76.png', 'install_night', '138 Country Club Drive, Commack 11725', (select id from public.customers where left(id::text,8) = 'a27de417' limit 1), 'a27de417', 'Vincent Barbieri', false, 'pending', null),
  ('1ZsgN_vOiZsdfZKxVjnjFG3LAhWPCdWd1', 'Homes Without Logo (numbered img###.png)', 'img77.png', 'install_night', '7 birch road amityville ny', null, null, null, false, 'pending', null),
  ('1VO8v5cwJAgAtxE3Vhk-_1EukrzvRX4jW', 'Homes Without Logo (numbered img###.png)', 'img78.png', 'install_night', '10 Ashland Drive, Huntington 11743', (select id from public.customers where left(id::text,8) = '878ae1c9' limit 1), '878ae1c9', 'Andrew Bykov', false, 'pending', null),
  ('1MlfcQVAkX0I9QSItnJA3lYeN55WPMY44', 'Homes Without Logo (numbered img###.png)', 'img80.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1-vGuhFwtZYqdkRrU7YdRB5NOd1TJWDqj', 'Homes Without Logo (numbered img###.png)', 'img81.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1NZVpXbNeLEvqZzK4kOUtMzqRHP7FBipM', 'Homes Without Logo (numbered img###.png)', 'img82.png', 'install_night', '6 Maggie Court, Nesconset, New York 11767', null, null, null, false, 'pending', null),
  ('1g-pKEViW2kB0XwLPQJwSoa1yqukYoIWj', 'Homes Without Logo (numbered img###.png)', 'img83.png', 'install_night', '6 Maggie Court, Nesconset, New York 11767', null, null, null, false, 'pending', null),
  ('1vCg48-Gnke04TGJ_fffIAeK8yUm2lfWl', 'Homes Without Logo (numbered img###.png)', 'img84.png', 'install_night', '506 Devon Place, West Islip 11795', (select id from public.customers where left(id::text,8) = '1f9d1eea' limit 1), '1f9d1eea', 'Chris Kourounis', false, 'pending', null),
  ('1Z4GeYPrE-NdCSC5wdF34S_sw5_l84BYU', 'Homes Without Logo (numbered img###.png)', 'img85.png', 'install_night', '134 Larsen Drive, Amityville 11701', (select id from public.customers where left(id::text,8) = '94993ae6' limit 1), '94993ae6', 'Mr. Albert Belcher', false, 'pending', null),
  ('1jEO0IT2Rbt7NyRlK5iQGE7p5V0x3Hin_', 'Homes Without Logo (numbered img###.png)', 'img86.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1mDKCk8e2T1S8nA5sIjhwJiHq87de_4R3', 'Homes Without Logo (numbered img###.png)', 'img87.png', 'install_night', '44 Wavecrest Avenue, West Islip, New York 11795', null, null, null, false, 'pending', null),
  ('1elbvh3PB0W3STxYimM2tWuFLpcN3wv0R', 'Homes Without Logo (numbered img###.png)', 'img89.png', 'install_night', '100 Browns, Huntington, NY 11743', null, null, null, false, 'pending', null),
  ('1_Wn15rAaiWMUl0tdjWuLKU-KosPdQbwx', 'Homes Without Logo (numbered img###.png)', 'img90.png', 'install_night', '100 Browns, Huntington, NY 11743', null, null, null, false, 'pending', null),
  ('1zUqSHbv08W1tAqVJxiswxupuIDmt2Rq0', 'Homes Without Logo (numbered img###.png)', 'img91.png', 'install_night', '14 Hadland Drive, Huntington, New York 11743', null, null, null, false, 'pending', null),
  ('1EViGGiRGm4sF1v4tsNh4fxhYmatJnn3P', 'Homes Without Logo (numbered img###.png)', 'img92.png', 'install_night', '204 Vineyard Road Halesite', null, null, null, false, 'pending', null),
  ('15wcJCjk83FJOhXIwTOQ3WeK0LUm9uuvy', 'Homes Without Logo (numbered img###.png)', 'img93.png', 'install_night', '14 Hadland Drive, Huntington, New York 11743', null, null, null, false, 'pending', null),
  ('12WfmdIlLfZGulWJ1Oivwb9hCCXMmaUjh', 'Homes Without Logo (numbered img###.png)', 'img94.png', 'install_night', '261 Manhattan Avenue West Babylon', null, null, null, false, 'pending', null),
  ('1fpLTdNzQF_yWZ8SnpBCyXjHBX-e4217M', 'Homes Without Logo (numbered img###.png)', 'img95.png', 'install_night', '79 Court St, West Babylon, NY 11704', null, null, null, false, 'pending', null),
  ('1ZKORKv18OPmoK4eDdUSqqM5IUkG8xc1z', 'Homes Without Logo (numbered img###.png)', 'img96.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1l0HeII9BHJH5UPLTKKqR95ZADQVpEuE9', 'Homes Without Logo (numbered img###.png)', 'img97.png', 'install_night', '8 Birch Rd, Amityville, NY 11701', null, null, null, false, 'pending', null),
  ('1eimNXoCo8tesV-sKGRv_kipeeSK3DHqU', 'Homes Without Logo (numbered img###.png)', 'img99.png', 'install_night', '160 Brewster Rd, Massapequa, NY 11758', null, null, null, false, 'pending', null),
  ('1XLYqI4CA6DwIG71frmZSz6-j3ADIcu1x', 'Homes Without Logo (numbered img###.png)', 'img100.png', 'install_night', '3504 Howard Boulevard Baldwin', null, null, null, false, 'pending', null),
  ('1AmsShh7NhA_-dLNfvbvkZ_Mu1GU3Fjvx', 'Homes Without Logo (numbered img###.png)', 'img101.png', 'install_night', '231 Tinton Place, East Northport 11731', (select id from public.customers where left(id::text,8) = '9c6922b2' limit 1), '9c6922b2', 'John Pierson', false, 'pending', null),
  ('1s_0ebMbUH7vH7dyY7I-7FKPxU08jpSOm', 'Homes Without Logo (numbered img###.png)', 'img102.png', 'install_night', '5 Mason Court, East Northport 11731', (select id from public.customers where left(id::text,8) = '98710a65' limit 1), '98710a65', 'Carl Laurent', false, 'pending', null),
  ('1Xp93Uc-6u-EcMwAYvlGIYxQBEOTrHvB0', 'Homes Without Logo (numbered img###.png)', 'img103.png', 'install_night', '9 Norman Avenue, Amityville 11701', (select id from public.customers where left(id::text,8) = 'a802182e' limit 1), 'a802182e', 'John Filosa', false, 'pending', null),
  ('1uqXUO7TXEVwXUNkT_vpGkqqZvdr3EEj9', 'Homes Without Logo (numbered img###.png)', 'img104.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('18U0hnrcSeavqgz6fmCHzU02DmAqbMVtX', 'Homes Without Logo (numbered img###.png)', 'img105.png', 'install_night', '131 Grand Avenue Lindenhurst', null, null, null, false, 'pending', null),
  ('1JtJRRoSMul7fz7F8LwLccSk5AlRhWohx', 'Homes Without Logo (numbered img###.png)', 'img106.png', 'install_night', '8 Miller Road, Farmingdale, New York 11735', null, null, null, false, 'pending', null),
  ('1IZCjzFYdpfMkm5iRTk33qAI2rGNYaeb4', 'Homes Without Logo (numbered img###.png)', 'img107.png', 'install_night', '14 Hadland Drive, Huntington, New York 11743', null, null, null, false, 'pending', null),
  ('1ZrA-vx1_Gsu5AJV79DYaENYkVfu59fAe', 'Homes Without Logo (numbered img###.png)', 'img108.png', 'install_night', '18 Daisy Court Farmingdale', null, null, null, false, 'pending', null),
  ('1C41JIVYU2hvWqONrJc01cQRTvGgyYS1Z', 'Homes Without Logo (numbered img###.png)', 'img109.png', 'install_night', '494 Belmore Avenue, Islip Terrace 11752', (select id from public.customers where left(id::text,8) = '61fc031f' limit 1), '61fc031f', 'Mark Benner', false, 'pending', null),
  ('1tCl7QjpWPGRloUkxzTjHsrzLvGBntr6C', 'Homes Without Logo (numbered img###.png)', 'img110.png', 'install_night', '3775 New York Avenue, Seaford 11783', (select id from public.customers where left(id::text,8) = 'f1f7d096' limit 1), 'f1f7d096', 'Kathy Polera', false, 'pending', null),
  ('1D_eGH8SpntZSGJruM2jAaEp-ufZsuuNN', 'Homes Without Logo (numbered img###.png)', 'img111.png', 'install_night', '155 Schleigel Boulevard, Amityville, New York 11701', null, null, null, false, 'pending', null),
  ('15aju2ZDrGC25UFB3hlVH_JdVArhwvgBQ', 'Homes Without Logo (numbered img###.png)', 'img112.png', 'install_night', '230 W 24th StDeer Park, NY 11729.', null, null, null, false, 'pending', null),
  ('1DL3v1-b-BpAuYI6s5NbwQWJSXsAbF8FV', 'Homes Without Logo (numbered img###.png)', 'img113.png', 'install_night', '35 Hewes Street, Port Jefferson Station 11776', (select id from public.customers where left(id::text,8) = '1dcd0c94' limit 1), '1dcd0c94', 'Ken Hanlon', false, 'pending', null),
  ('1Jvx_BCpfQ9KN6kv_SqNT8XSnpadojtR8', 'Homes Without Logo (numbered img###.png)', 'img114.png', 'install_night', '9 high ridge lane oyster bay', null, null, null, false, 'pending', null),
  ('11ZTlMAg3VTSULISL-Qpt0QUQJXU6FozJ', 'Homes Without Logo (numbered img###.png)', 'img115.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1gzqDuAAIbqQa82X59OLJlJOnIoP9ageg', 'Homes Without Logo (numbered img###.png)', 'img116.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1gca_CHnIYqbpuqdcCkyEi1xhHapvz3Cl', 'Homes Without Logo (numbered img###.png)', 'img118.png', 'install_night', '426 Wolf Hill Road Dix Hills', null, null, null, false, 'pending', null),
  ('14VTekhTzyximA0TW91ScylBjt-5OxkLt', 'Homes Without Logo (numbered img###.png)', 'img119.png', 'install_night', '231 Tinton Place, East Northport 11731', (select id from public.customers where left(id::text,8) = '9c6922b2' limit 1), '9c6922b2', 'John Pierson', false, 'pending', null),
  ('1ErfToqkcZoOXDS3RIHkUweKZZZtaOeVP', 'Homes Without Logo (numbered img###.png)', 'img120.png', 'install_night', '231 Tinton Place, East Northport 11731', (select id from public.customers where left(id::text,8) = '9c6922b2' limit 1), '9c6922b2', 'John Pierson', false, 'pending', null),
  ('1lrs34h8p8hlGj1mZfEypxDRXv0EB7g0K', 'Homes Without Logo (numbered img###.png)', 'img121.png', 'install_night', '19 Village Lane Hauppauge', null, null, null, false, 'pending', null),
  ('1USIMhZLW6cIXV0ua2eYA86CsnsoSoIjD', 'Homes Without Logo (numbered img###.png)', 'img122.png', 'install_night', '2 Tap Court, Nesconset 11767', (select id from public.customers where left(id::text,8) = 'a6598fcc' limit 1), 'a6598fcc', 'Raymond Brown', false, 'pending', null),
  ('1iYNGYL9_bMB7doCUkWF001tVQIBhA6ZN', 'Homes Without Logo (numbered img###.png)', 'img123.png', 'install_night', '1530 Old Country Rd, Westbury, NY 11590', null, null, null, false, 'pending', null),
  ('1Rm6UNoCBzZps7FKJHzwKuqAgd2zoPN5N', 'Homes Without Logo (numbered img###.png)', 'img124.png', 'install_night', '230 W 24th St Deer Park, NY 11729', null, null, null, false, 'pending', null),
  ('1e4aHftAdpNqfpyleMATrVaiDTM40HKT2', 'Homes Without Logo (numbered img###.png)', 'img125.png', 'install_night', '160 Brewster Rd, Massapequa, NY 11758', null, null, null, false, 'pending', null),
  ('1pouQtxeAfClp7fcfze45djZBHiv-B02Y', 'Homes Without Logo (numbered img###.png)', 'img126.png', 'install_night', '8 Birch Rd, Amityville, NY 11701', null, null, null, false, 'pending', null),
  ('1BaSTRPjdnPDu-431JfO2lnNNXspH-5i5', 'Homes Without Logo (numbered img###.png)', 'img127.png', 'install_night', '13 Brown Boulevard, Wyandanch 11798', (select id from public.customers where left(id::text,8) = '3b822e9a' limit 1), '3b822e9a', 'Mrs. Mrs. Jones', false, 'pending', null),
  ('1zp1hZQ2GEHrb9uuJLWQI6Kioq4Q8b6Sc', 'Homes Without Logo (numbered img###.png)', 'img128.png', 'install_night', '3504 Howard Boulevard Baldwin', null, null, null, false, 'pending', null),
  ('12_sACLqn1QtXb4U_0us8RK9jYwfbEZ9-', 'Homes Without Logo (numbered img###.png)', 'img129.png', 'install_night', '4 Birch Rd, Amityville, NY 11701', null, null, null, false, 'pending', null),
  ('1iK2-mej7pKrcea1lUucxzipXRNa0iT7a', 'Homes Without Logo (numbered img###.png)', 'img130.png', 'install_night', '13 Brown Boulevard, Wyandanch 11798', (select id from public.customers where left(id::text,8) = '3b822e9a' limit 1), '3b822e9a', 'Mrs. Mrs. Jones', false, 'pending', null),
  ('1PNV8iPPNFlaybhuN3iMRRKjiYL76P7qW', 'Homes Without Logo (numbered img###.png)', 'img131.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1bwvsEJ7G4tHSuFFSRQEJHV3ZHEUDsD6L', 'Homes Without Logo (numbered img###.png)', 'img132.png', 'install_night', '160 Brewster Rd, Massapequa, NY 11758', null, null, null, false, 'pending', null),
  ('1njEIbD8sme8kegtBgCQJupFZ3s8SniSB', 'Homes Without Logo (numbered img###.png)', 'img133.png', 'install_night', '13 Brown Boulevard, Wyandanch 11798', (select id from public.customers where left(id::text,8) = '3b822e9a' limit 1), '3b822e9a', 'Mrs. Mrs. Jones', false, 'pending', null),
  ('1mA1GHR6cpNATLMix3Nd5BDhZfz_E_Y9W', 'Homes Without Logo (numbered img###.png)', 'img134.png', 'install_night', '155 Schleigel Boulevard, Amityville, New York 11701', null, null, null, false, 'pending', null),
  ('1MhOMaxFLqlyk8MTxlg5srI7UvOCIjOcX', 'Homes Without Logo (numbered img###.png)', 'img135.png', 'install_night', '345 Litchfield Avenue, Elmont, New York 11003', null, null, null, false, 'pending', null),
  ('1vBEPoZR3eDqvmfB5SnPBXFKl725lAGPr', 'Homes Without Logo (numbered img###.png)', 'img136.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1n7WJ9ye649j_t0NFmfIa1G_8m9bmJ58u', 'Homes Without Logo (numbered img###.png)', 'img137.png', 'install_night', '6 Maggie Court, Nesconset, New York 11767', null, null, null, false, 'pending', null),
  ('1wmpv4AjE0FQYIfdsshqodpAK4Ext8Jc8', 'Homes Without Logo (numbered img###.png)', 'img138.png', 'other', null, null, null, null, false, 'excluded', null),
  ('14LXywh5RxAy-1koxvCmKkbUAZuAv8S0m', 'Homes Without Logo (numbered img###.png)', 'img139.png', 'install_night', '345 Litchfield Avenue, Elmont, New York 11003', null, null, 'farooq fatima -', false, 'pending', null),
  ('19fGlc_UbZW3tdDwvLGnCrUKCsSc5FtdJ', 'Homes Without Logo (numbered img###.png)', 'img140.png', 'install_night', '345 Litchfield Avenue, Elmont, New York 11003', null, null, null, false, 'pending', null),
  ('1B9ZOluJcUwiu63NOC02lMGrPwNppgn1-', 'Homes Without Logo (numbered img###.png)', 'img141.png', 'install_night', '6 Maggie Court, Nesconset, New York 11767', null, null, null, false, 'pending', null),
  ('1LJQFDMAOGK-XymcC-eW5f5jYQDGt9Z_x', 'Homes Without Logo (numbered img###.png)', 'img142.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1lfH3ctXvmIQbTqLDch3xX1dVECA2NP6M', 'Homes Without Logo (numbered img###.png)', 'img143.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1mMNQZa4812RUvgpMq-Is8hI826URD9u1', 'Homes Without Logo (numbered img###.png)', 'img144.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1GMo6bbShl7bjjj4R1Va5F_mRc5eilPo1', 'Homes Without Logo (numbered img###.png)', 'img145.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1N485HN16H8_Z3c04Emleau3MDyOX6BFX', 'Homes Without Logo (numbered img###.png)', 'img146.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1UN_1KSeugXSuH98ZQQwNn-WbBBtfFI1R', 'Homes Without Logo (numbered img###.png)', 'img147.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1RVLbzxETqWcCP1dI4i6WuQOZkatgl1Bt', 'Homes Without Logo (numbered img###.png)', 'img148.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1Hio3L9TKVzGLjNn3gLdsM_sdFOjexvNx', 'Homes Without Logo (numbered img###.png)', 'img149.png', 'install_night', '6 birch road amityville ny 11701', null, null, null, false, 'pending', null),
  ('1Q83WrNgvSsx01ohWInkeTkHGViSFXFUB', 'Homes Without Logo (numbered img###.png)', 'img150.png', 'install_night', '6 birch road amityville ny 11701', null, null, null, false, 'pending', null),
  ('1DY63TbcBQkA6KOwCiaIW80Xtuwzuvi3R', 'Homes Without Logo (numbered img###.png)', 'img151.png', 'install_night', '6 birch road amityville ny 11701', null, null, null, false, 'pending', null),
  ('1vMTCtil57nF38-rlU5fSzvK6l3fUdp2q', 'Homes Without Logo (numbered img###.png)', 'img152.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1CTjRCs3rVFNU7RTfd42qJTZg-bYWFqfQ', 'Homes Without Logo (numbered img###.png)', 'img153.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1Ol8XytzGDzljE5-ZQsawXNc436atbkmL', 'Homes Without Logo (numbered img###.png)', 'img154.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1mqUB6xC9Mm4Ak1i3IuwOul0hSR9HyEVi', 'Homes Without Logo (numbered img###.png)', 'img155.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1ob6yqso2T8WmHv55Kn_3bUftyt7ewzyw', 'Homes Without Logo (numbered img###.png)', 'img156.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1V6rZ-1jGLWPeaU5IUExBXkFOPzHsllWc', 'Homes Without Logo (numbered img###.png)', 'img157.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1AEQ6RsrjL7iSkAYz1OJGx4k0LSD9S70A', 'Homes Without Logo (numbered img###.png)', 'img158.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1VGebas1qPrkvsl32AA1Z7UwBtECWtU_3', 'Homes Without Logo (numbered img###.png)', 'img159.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1JB-erwHDcRzwIYjj5OEbEx6lXWGv4mvf', 'Homes Without Logo (numbered img###.png)', 'img160.png', 'install_night', '155 Schleigel Boulevard, Amityville, New York 11701', null, null, null, false, 'pending', null),
  ('1tSY5wHTOuMvW-wJcWrEh9o6WRJ0hkrnS', 'Homes Without Logo (numbered img###.png)', 'img161.png', 'other', null, null, null, null, false, 'excluded', null),
  ('13bu4HiJC8bTl61830wxRyxLp2U1Yi_cW', 'Homes Without Logo (numbered img###.png)', 'img162.png', 'install_night', '129 Hilton Avenue Hempstead', null, null, null, false, 'pending', null),
  ('1ATb8-3ooZEcAjFa_JEMafh-qWp4ednD0', 'Homes Without Logo (numbered img###.png)', 'img163.png', 'install_night', '129 Hilton Avenue Hempstead', null, null, null, false, 'pending', null),
  ('1xd6QPmU7_sPs11DKrMWIJvZKL1Cvtyj7', 'Homes Without Logo (numbered img###.png)', 'img164.png', 'install_night', '9 Norman Avenue, Amityville 11701', (select id from public.customers where left(id::text,8) = 'a802182e' limit 1), 'a802182e', 'John Filosa', false, 'pending', null),
  ('1fxcjpoWynABKWyFXY75z9s5u1h9jRB0Y', 'Homes Without Logo (numbered img###.png)', 'img165.png', 'install_night', '129 Hilton Avenue Hempstead', null, null, null, false, 'pending', null),
  ('1dK-uWCyNxAfw2Yi78lbN56lkcI06X_V3', 'Homes Without Logo (numbered img###.png)', 'img166.png', 'other', null, null, null, null, false, 'excluded', null),
  ('16mkx85xtukUCVoDsIUv-yXMYvd-4Y3zq', 'Homes Without Logo (numbered img###.png)', 'img167.png', 'install_night', '14 Hadland Drive, Huntington, New York 11743', null, null, null, false, 'pending', null),
  ('16mZt79Y2gHgrDjVVUBp74qxh9HFLbetl', 'Homes Without Logo (numbered img###.png)', 'img168.png', 'install_night', '38 Miller Road, Farmingdale, New York 11735', null, null, null, false, 'pending', null),
  ('1Q9y84vHncdKMVJdkD9ae8daodTAnPfSr', 'Homes Without Logo (numbered img###.png)', 'img169.png', 'install_night', '14 Hadland Drive, Huntington, New York 11743', null, null, null, false, 'pending', null),
  ('1Hz49OJ0Wj2wNIwASlBjeDFgwg4MRWK7F', 'Homes Without Logo (numbered img###.png)', 'img170.png', 'install_night', '38 Miller Road, Farmingdale, New York 11735', null, null, null, false, 'pending', null),
  ('1GvRPPoGbA_1IK0fgJ6L0vs2v9ViI3Joe', 'Homes Without Logo (numbered img###.png)', 'img171.png', 'other', null, null, null, null, false, 'excluded', null),
  ('13mgyGxjr_E_N0Dap03tzqvjpLO3MOEij', 'Homes Without Logo (numbered img###.png)', 'img172.png', 'install_night', '131 Grand Avenue Lindenhurst', null, null, null, false, 'pending', null),
  ('187AXAM-m6awJmnr0Fsud3t_Vxr6RS-s7', 'Homes Without Logo (numbered img###.png)', 'img173.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1FOQ1BJlbiD0ZML-wU9Zu66c3fj7crhC9', 'Homes Without Logo (numbered img###.png)', 'img174.png', 'install_night', '35 Hewes Street, Port Jefferson Station 11776', (select id from public.customers where left(id::text,8) = '1dcd0c94' limit 1), '1dcd0c94', 'Ken Hanlon', false, 'pending', null),
  ('1VRSNi5qU-xQgCSlPN8SC-Q61jZiR1E-6', 'Homes Without Logo (numbered img###.png)', 'img175.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1UeM95L1mn0TBQ-sehQq1fd0feRWFuVwD', 'Homes Without Logo (numbered img###.png)', 'img176.png', 'install_night', '3775 New York Avenue, Seaford 11783', (select id from public.customers where left(id::text,8) = 'f1f7d096' limit 1), 'f1f7d096', 'Kathy Polera', false, 'pending', null),
  ('1F97YPNlLXLydRpNaNzYfEHTm4aqCKu9o', 'Homes Without Logo (numbered img###.png)', 'img177.png', 'install_night', '494 Belmore Avenue, Islip Terrace 11752', (select id from public.customers where left(id::text,8) = '61fc031f' limit 1), '61fc031f', 'Mark Benner', false, 'pending', null),
  ('1q-yEsaeUet2FOyaS9fWq73GVDYz2cl6j', 'Homes Without Logo (numbered img###.png)', 'img178.png', 'install_night', '18 Daisy Court, Farmingdale, New York 11735', null, null, null, false, 'pending', null),
  ('12Z6_VhrrPIha2t5fqnyyW9BpvQjO5V4Q', 'Homes Without Logo (numbered img###.png)', 'img179.png', 'install_night', '575 North Fulton Avenue, Lindenhurst 11757', (select id from public.customers where left(id::text,8) = 'ae8f3367' limit 1), 'ae8f3367', 'Kristie Tibbetts', false, 'pending', null),
  ('1g_goJaOctDUuWtLh6p6Lkq8GVIPsHH0j', 'Homes Without Logo (numbered img###.png)', 'img180.png', 'install_night', '120 Avoca Avenue, Massapequa Park 11762', (select id from public.customers where left(id::text,8) = '68a6b7fc' limit 1), '68a6b7fc', 'Nancy Belski', false, 'pending', null),
  ('191X_VHVvt9Kz5dKW_9pl4ZlMhN-ETvIX', 'Homes Without Logo (numbered img###.png)', 'img181.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1fIQ-UBMpvIVn2-R5sEQqS-vbsh5MpDXN', 'Homes Without Logo (numbered img###.png)', 'img182.png', 'install_night', '2 Marriott Plaza, Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('13WGX2v5i4z4lhIrd_icEiJzHxzSEengL', 'Homes Without Logo (numbered img###.png)', 'img183.png', 'install_night', '160 Brewster Rd, Massapequa, NY 11758', null, null, null, false, 'pending', null),
  ('1NWF9MSenFm4sChvKDrPVrMsz6g4RtMBG', 'Homes Without Logo (numbered img###.png)', 'img184.png', 'install_night', '44 Wavecrest Avenue, West Islip, New York 11795', null, null, null, false, 'pending', null),
  ('1HiThH8pUIOk9WUlXw1_6tysQUMG56zsx', 'Homes Without Logo (numbered img###.png)', 'img185.png', 'install_night', '319 West 15th Street Deer Park', null, null, null, false, 'pending', null),
  ('1JHkobH_fVBMzYlUXZ7kCC3jNpJenqJRL', 'Homes Without Logo (numbered img###.png)', 'img186.png', 'install_night', '35 Hewes Street, Port Jefferson Station 11776', (select id from public.customers where left(id::text,8) = '1dcd0c94' limit 1), '1dcd0c94', 'Ken Hanlon', false, 'pending', null),
  ('1FctLBpXYrZby090v4aFoN0VJ_BPruAAR', 'Homes Without Logo (numbered img###.png)', 'img187.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1TRxWEMaOgoyCWDZeMnA2g50EKPgj52ZO', 'Homes Without Logo (numbered img###.png)', 'img188.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1jeDV5QS2xohq8brgY0-HdxO7J5iZtAUj', 'Homes Without Logo (numbered img###.png)', 'img189.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1o8VQbo2E7K9bFyynsB9gmg9hbWvl4-Sc', 'Homes Without Logo (numbered img###.png)', 'img190.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1G1dhtod5NQUHCcoaLv91quMTWRypjUFq', 'Homes Without Logo (numbered img###.png)', 'img192.png', 'install_night', '13 Brown Boulevard, Wyandanch 11798', (select id from public.customers where left(id::text,8) = '3b822e9a' limit 1), '3b822e9a', 'Mrs. Mrs. Jones', false, 'pending', null),
  ('1aL58PlN6i5pblb1GseslH76GUn4dvabw', 'Homes Without Logo (numbered img###.png)', 'img193.png', 'install_night', '638 WILSON BLVD CENTRAL ISLIP NY', null, null, null, false, 'pending', null),
  ('1SsFWqEUbn2WE_L3DTukN8M1a-MXye8of', 'Homes Without Logo (numbered img###.png)', 'img194.png', 'install_night', '44 Wavecrest Avenue, West Islip, New York 11795', null, null, null, false, 'pending', null),
  ('1cuCn5bHsyjHcI-lY9dH8YiFvD7LefOiW', 'Homes Without Logo (numbered img###.png)', 'img195.png', 'install_night', '64 Sagebrush Lane Islandia', null, null, null, false, 'pending', null),
  ('1K99TxdAeWaoEjJIzsLO9dzpBpPerVn5y', 'Homes Without Logo (numbered img###.png)', 'img196.png', 'install_night', '638 WILSON BLVD CENTRAL ISLIP NY', null, null, null, false, 'pending', null),
  ('1mRjLDxPpClGNMIXPG1htRNfEs9-oKeqB', 'Homes Without Logo (numbered img###.png)', 'img197.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1G9lAlWHu7TuD7I3047xTMZitIlEdX9ul', 'Homes Without Logo (numbered img###.png)', 'img198.png', 'install_night', '1991 Broadhollow Rd Farmingdale, NY 11735', null, null, null, false, 'pending', null),
  ('1WK1nesdnzcBr1CRaxUVTKLcMa5f93Go4', 'Homes Without Logo (numbered img###.png)', 'img199.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1SEOd1GwT_Z_Cw95pKK7hdHBz0_7gb3kl', 'Homes Without Logo (numbered img###.png)', 'img200.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1ZTw1cNtE50HFgXhx_5WZ8qbHbaG_MgWy', 'Homes Without Logo (numbered img###.png)', 'img201.png', 'other', null, null, null, null, false, 'excluded', null),
  ('1YpEZ24cA3griJzC-az4qSVuyFkZ-_LTH', 'Homes Without Logo (numbered img###.png)', 'img202.png', 'install_night', '13 Brown Boulevard, Wyandanch 11798', (select id from public.customers where left(id::text,8) = '3b822e9a' limit 1), '3b822e9a', 'Mrs. Mrs. Jones', false, 'pending', null),
  ('10XU5DCN7vaLuYWlcthESfgevkXLPMZUp', 'Homes Without Logo (numbered img###.png)', 'img203.png', 'install_night', '69 31st street wyandanch', null, null, null, true, 'pending', 'address typed manually; no CRM contact matched'),
  ('1gJuFKRTbkfPUXUAjJBdTgZgIOiG7PdnF', 'Homes Without Logo (numbered img###.png)', 'img204.png', 'other', null, null, null, null, false, 'excluded', null)
on conflict (drive_file_id) do nothing;

-- ---------------------------------------------------------------------
-- VERIFY (read the output — do not skip). Expected: 211 loaded,
-- 0 unresolved customer links, 29 distinct customers linked.
-- ---------------------------------------------------------------------
select
  (select count(*) from public.archive_photos)                                  as total_rows,
  (select count(*) from public.archive_photos where status = 'pending')         as pending,
  (select count(*) from public.archive_photos where status = 'excluded')        as excluded,
  (select count(distinct resolved_customer_id) from public.archive_photos
     where resolved_customer_id is not null)                                    as customers_linked,
  (select count(*) from public.archive_photos
     where resolved_customer_ref is not null and resolved_customer_id is null)  as unresolved_links,
  (select count(distinct resolved_address_key) from public.archive_photos
     where resolved_address_key is not null)                                    as distinct_properties;

-- Any row listed here had a customer prefix that no longer resolves — re-link
-- it by hand (resolved_name says who it should be). Empty result = all good.
select drive_file_id, original_title, resolved_name, resolved_customer_ref
from public.archive_photos
where resolved_customer_ref is not null and resolved_customer_id is null
order by original_title;
